(source gnu)
(source melpa)

(depends-on "ac-helm")
(depends-on "bind-key")
(depends-on "cask")
(depends-on "color-theme")
(depends-on "dash")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "fiplr")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "flycheck-flow")
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-core")
(depends-on "helm-projectile")
(depends-on "helm-spotify")
(depends-on "highlight-indentation")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "neotree")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "pt")
(depends-on "s")
(depends-on "use-package")
(depends-on "vagrant-tramp")
(depends-on "zencoding-mode")

;; editing support
(depends-on "sr-speedbar")
(depends-on "yasnippet")
(depends-on "auto-complete")
(depends-on "dropdown-list")
(depends-on "expand-region")

;; document modes
(depends-on "markdown-mode")
(depends-on "sass-mode")
(depends-on "scss-mode")
(depends-on "slim-mode")
(depends-on "web-mode")
(depends-on "yaml-mode")
