(deftheme deeper-blue
  "Created 2016-06-27.")

(custom-theme-set-faces
 'deeper-blue
 '(info-title-1 ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.728))))
 '(info-title-2 ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.44))))
 '(info-title-3 ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.2))))
 '(info-title-4 ((((class color) (min-colors 89)) (:family "helv" :weight bold))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "LightGreen"))))
 '(compilation-error ((((class color) (min-colors 89)) (:foreground "Red1"))))
 '(compilation-info ((((class color) (min-colors 89)) (:weight normal :foreground "LightSkyBlue"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "LightGreen"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "blue4"))))
 '(cursor ((((class color) (min-colors 89)) (:background "green"))))
 '(dired-marked ((((class color) (min-colors 89)) (:background "dodgerblue3" :foreground "white"))))
 '(error ((((class color) (min-colors 89)) (:foreground "red"))))
 '(flymake-errline ((((class color) (min-colors 89)) (:background nil :underline "red"))))
 '(flymake-warnline ((((class color) (min-colors 89)) (:background nil :underline "magenta3"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "LightCoral"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "moccasin"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "gold"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "burlywood"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(fringe ((t (:background "#181A26"))))
 '(highlight ((((class color) (min-colors 89)) (:background "DodgerBlue4"))))
 '(info-header-node ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(info-menu-header ((((class color) (min-colors 89)) (:family "helv" :weight bold))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(info-xref ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(isearch ((((class color) (min-colors 89)) (:background "coral2" :foreground "white"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "coral4" :foreground "white"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "cadetblue" :foreground "white"))))
 '(match ((((class color) (min-colors 89)) (:background "DeepPink4"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(mode-line ((t (:background "#181A26" :foreground "gainsboro" :box nil))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold :background nil :foreground "DeepSkyBlue1"))))
 '(mode-line-inactive ((t (:background "#181A26" :foreground "black" :box nil))))
 '(outline-1 ((((class color) (min-colors 89)) (:foreground "SkyBlue1"))))
 '(outline-2 ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(outline-3 ((((class color) (min-colors 89)) (:foreground "LightSteelBlue1"))))
 '(outline-4 ((((class color) (min-colors 89)) (:foreground "turquoise2"))))
 '(outline-5 ((((class color) (min-colors 89)) (:foreground "aquamarine1"))))
 '(region ((((class color) (min-colors 89)) (:background "#103050"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "dodgerblue1" :foreground "white"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:background "red1" :foreground "white"))))
 '(success ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "Yellow"))))
 '(default ((((class color) (min-colors 89)) (:background "#181a26" :foreground "gray80")))))

(provide-theme 'deeper-blue)
